// entrypoints/popup2/src/App.vue
<script setup lang="ts">
  import { version } from "../../../package.json"
  import MdiToggleSwitch from "./components/icon/MdiToggleSwitch.vue"
  import MdiToggleSwitchOffOutline from "./components/icon/MdiToggleSwitchOffOutline.vue"

  import { useToggle } from "@vueuse/core"
  import {
    AllSettingsKeys,
    KeyExtensionStatus,
    KeyTimelineWidth,
  } from "../../../storage-keys"
  import { getStorage, setStorage } from "../../../utils/chromeStorage"
  import { onMounted, ref, watch } from "vue"

  const [enable, toggleEnable] = useToggle()
  const allSettings = ref<Record<string, string | number>>()
  watch(allSettings, (_allSettings) => {
    toggleEnable(_allSettings?.[KeyExtensionStatus] === "on")
  })

  function updateAllSettings() {
    getStorage(AllSettingsKeys).then((val) => {
      allSettings.value = val
    })
  }

  function changeKeyExtensionStatus() {
    setStorage({
      [KeyExtensionStatus]: enable.value ? "off" : "on",
    }).then(() => {
      updateAllSettings()
    })
  }

  function changeKeyTimelineWidth(e: Event) {
    const w = +(e.target as HTMLInputElement).value
    setStorage({
      [KeyTimelineWidth]: Math.max(600, Math.min(w, 1200)),
    }).then(() => {
      updateAllSettings()
    })
  }

  onMounted(() => {
    updateAllSettings()
  })
</script>

<template>
  <div class="p2 w-300px flex flex-col gap-2">
    <div class="box xy-between">
      <div>
        <span class="font-bold text-xl">okjike-ui</span>
        <span class="mx-1 text-xs op50">v{{ version }}</span>
      </div>
      <div
        class="xy-center w-6 h-6 cursor-pointer c-#fbe54f"
        @click="changeKeyExtensionStatus()"
      >
        <MdiToggleSwitch
          v-if="enable"
          class="w-100% h-100%"
        />
        <MdiToggleSwitchOffOutline
          v-else
          class="w-100% h-100%"
        />
      </div>
    </div>
    <div class="box xy-between">
      <div>时间线</div>
      <div>
        <input
          type="number"
          :value="allSettings?.[KeyTimelineWidth]"
          min="400"
          max="1000"
          @change="changeKeyTimelineWidth"
        />
        <span>px</span>
      </div>
    </div>
    <div class="box">
      <pre>{{ JSON.stringify(allSettings, null, 2) }}</pre>
    </div>
  </div>
</template>

// entrypoints/popup/src/App.tsx
import { useEffect, useState } from "react"
import { InputNumber, Radio, Switch } from "antd"

import { version } from "../../../package.json"
import { getStorage, setStorage } from "../../../utils/chromeStorage"
import {
  AllSettingsKeys,
  KeyExtensionStatus,
  KeyTimelineLayout,
  KeyTimelineWidth,
  KeyTimelinePostAlign,
} from "../../../storage-keys"

export default function App() {
  const [devMode, setDevMode] = useState<boolean>(false)

  const [enable, setEnable] = useState<boolean>()
  const [enableTimelinePostAlign, setEnableTimelinePostAlign] =
    useState<boolean>()

  const [allSettings, setAllSettings] = useState<
    Record<string, string | number>
  >({})
  useEffect(() => {
    setEnable(allSettings[KeyExtensionStatus] === "on")
    setEnableTimelinePostAlign(allSettings[KeyTimelinePostAlign] === "on")
  }, [allSettings])

  function updateAllSettings() {
    getStorage(AllSettingsKeys).then((val) => {
      setAllSettings(val)
    })
  }

  function changeKeyExtensionStatus() {
    setStorage({
      [KeyExtensionStatus]: enable ? "off" : "on",
    }).then(() => {
      updateAllSettings()
    })
  }

  function changeKeyTimelineWidth(w: number) {
    setStorage({
      [KeyTimelineWidth]: w,
    }).then(() => {
      updateAllSettings()
    })
  }

  function changeKeyTimelineLayout(layout: string) {
    setStorage({
      [KeyTimelineLayout]: layout,
    }).then(() => {
      updateAllSettings()
    })
  }

  function changeKeyTimelinePostAlign(b: boolean) {
    setStorage({
      [KeyTimelinePostAlign]: b ? "on" : "off",
    }).then(() => {
      updateAllSettings()
    })
  }

  useEffect(() => {
    updateAllSettings()
  }, [])

  return (
    <div className="p2 w-300px flex flex-col gap-2 select-none text-base">
      <div className="box xy-between">
        <div>
          <span className="font-bold text-xl">okjike-ui</span>
          <span
            className="mx-1 text-xs op50 cursor-pointer"
            onDoubleClick={() => {
              setDevMode(!devMode)
            }}
          >
            v{version}
          </span>
        </div>
        <Switch
          value={enable}
          onChange={changeKeyExtensionStatus}
        />
      </div>
      <div className="box flex flex-col gap2">
        <div className="xy-between">
          <div>时间线宽度</div>
          <InputNumber
            className="w-100px"
            min={500}
            max={1400}
            controls={false}
            addonAfter={"px"}
            value={allSettings[KeyTimelineWidth]}
            onChange={(v) => {
              if (v) {
                changeKeyTimelineWidth(+v >> 0)
              }
            }}
          />
        </div>
        <div className="xy-between">
          <div>内容与头像对齐</div>
          <Switch
            value={enableTimelinePostAlign}
            onChange={changeKeyTimelinePostAlign}
          />
        </div>
      </div>
      <div className="box flex flex-col gap2">
        {/* 布局 */}
        <div className="xy-between">
          <div>布局</div>
          <Radio.Group
            options={[
              { label: "默认", value: "default" },
              { label: "瀑布流", value: "waterfall" },
            ]}
            optionType="button"
            value={allSettings[KeyTimelineLayout]}
            onChange={(e) => {
              changeKeyTimelineLayout(e.target.value)
            }}
          />
        </div>
      </div>
      <div
        className="box"
        hidden={!devMode}
      >
        <pre className="m0 text-xs">{JSON.stringify(allSettings, null, 2)}</pre>
      </div>
    </div>
  )
}
